#!/usr/bin/env bash

set -Eeuo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_ROOT="$(cd "$SCRIPT_DIR/.." && pwd)"
BASELINE_FILE="$SCRIPT_DIR/known-issues.txt"
ALLOWED_PORTS_FILE="$SCRIPT_DIR/allowed-ports.txt"

RELEASE_ENV="$REPO_ROOT/release.env"
COMPOSE_FILES=("$REPO_ROOT/compose.yaml" "$REPO_ROOT/compose.appbuilder.yaml")

SENSITIVE_KEYS=(
    MONGODB_PASSWORD JWT_SECRET ADMIN_SETUP_PASSWORD STATE_SECRET
    OPENID_SECRET_KEY OA_KEY SENDGRID_API_KEY GROQ_API_KEY HF_TOKEN
    VLLM_API_KEY GPU_VM_API_TOKEN APP_BUILDER_ANTHROPIC_API_KEY
    APP_BUILDER_GATEWAY_API_KEY NGC_API_KEY CLAUDE_API_KEY
)

NOT_SECRETS_DESPITE_THE_NAME=(
    GATEWAY_RPM_PER_KEY
    API_KEY_HASH_LAZY_MIGRATION
    API_KEY_HASH_NEW_KEYS
)

if [[ -t 1 ]]; then
    RED=$'\033[0;31m'; GREEN=$'\033[0;32m'; YELLOW=$'\033[1;33m'; BOLD=$'\033[1m'; NC=$'\033[0m'
else
    RED=""; GREEN=""; YELLOW=""; BOLD=""; NC=""
fi

FINDING_IDS=()
FINDING_MESSAGES=()

report() {
    FINDING_IDS+=("$1")
    FINDING_MESSAGES+=("$2")
}

env_keys() {
    grep -oE '^[A-Za-z_][A-Za-z0-9_]*=' "$RELEASE_ENV" | tr -d '='
}

keys_the_installer_generates() {
    grep -o 'GENERATED_SECRET_KEYS=([^)]*)' "$REPO_ROOT/ut-install" 2>/dev/null \
        | sed 's/.*(//; s/)//' | tr ' ' '\n'
    printf 'MONGODB_USERNAME\nMONGODB_PASSWORD\n'
}

keys_a_machine_will_have() {
    { env_keys; keys_the_installer_generates; } | sort -u
}

env_raw_value() {
    local key=$1 line
    line=$(grep -m1 -E "^${key}=" "$RELEASE_ENV" 2>/dev/null) || return 1
    line=${line#*=}
    line=${line%\"}; line=${line#\"}
    line=${line%\'}; line=${line#\'}
    printf '%s' "$line"
}

check_plaintext_secrets() {
    local key value
    for key in "${SENSITIVE_KEYS[@]}"; do
        value=$(env_raw_value "$key" 2>/dev/null) || continue
        [[ -z "$value" ]] && continue
        report "plaintext-secret:${key}" \
            "${key} ships a value in release.env — every deployment that follows the guide reuses it"
    done
}

# Wider than SENSITIVE_KEYS on purpose: compose.yaml reads HF_TOKEN and falls
# back to HF_API_TOKEN, which that nominative list never mentions.
check_release_env_ships_no_secret() {
    [[ -f "$RELEASE_ENV" ]] || return 0
    local key name exempt sensitive
    while read -r key; do
        [[ -n "$key" ]] || continue
        exempt=0
        for name in "${NOT_SECRETS_DESPITE_THE_NAME[@]}"; do
            if [[ "$key" == "$name" ]]; then exempt=1; fi
        done
        (( exempt == 0 )) || continue
        sensitive=0
        for name in "${SENSITIVE_KEYS[@]}"; do
            if [[ "$key" == "$name" ]]; then sensitive=1; fi
        done
        case "$key" in
            *_SECRET|*_TOKEN|*_PASSWORD|*_KEY|*_KEY_ID) sensitive=1 ;;
        esac
        (( sensitive )) || continue
        report "secret-in-release-env:${key}" \
            "${key} is declared in release.env, which the package ships world-readable — a secret belongs in local.env, generated by ut-install"
    done <<< "$(grep -oE '^[A-Za-z_][A-Za-z0-9_]*=' "$RELEASE_ENV" | tr -d '=')"
}

# release.env is not the only place a secret can ship from: a compose file
# writing ${JWT_SECRET:-something} carries that something into every deployment
# whose .env leaves the variable out. MONGODB_PASSWORD defaulted to 12345678
# here, which emptying release.env would not have touched.
check_compose_declares_no_secret_default() {
    local key default
    for key in "${SENSITIVE_KEYS[@]}"; do
        default=$(grep -ohE "\\\$\{${key}:-[^\\\${}]+\}" "${COMPOSE_FILES[@]}" 2>/dev/null | head -1) || continue
        [[ -n "$default" ]] || continue
        report "compose-secret-default:${key}" \
            "a compose file falls back to a value for ${key} (${default}) — it ships from here too"
    done
}

# A variable falling back to one value in one service and another elsewhere is
# a difference nobody chose. MONGODB_HOST read `mongodb` for the App Builder and
# the empty string for the seven services in compose.yaml, so an .env without
# that line started them against a database host of "".
check_healthcheck_asks_for_a_certified_name() {
    local url host names
    url=$(grep -h 'step", "ca", "health"' "${COMPOSE_FILES[@]}" 2>/dev/null \
        | grep -oE 'https://[^"]+' | head -1) || return 0
    [[ -n "$url" ]] || return 0
    host=${url#https://}; host=${host%%:*}
    names=$(grep -h 'DOCKER_STEPCA_INIT_DNS_NAMES' "${COMPOSE_FILES[@]}" 2>/dev/null) || return 0
    grep -q "[ ,:]${host}\(,\|$\)" <<< "$names" && return 0
    report "healthcheck-name-not-certified:${host}" \
        "the authority's healthcheck asks for ${host}, which DOCKER_STEPCA_INIT_DNS_NAMES does not list — it can never pass, and everything waiting on it stops"
}

seconds_in_duration() {
    local duration=$1 number=${1%[a-z]}
    case "$duration" in
        *h) printf '%s' $(( number * 3600 )) ;;
        *m) printf '%s' $(( number * 60 )) ;;
        *s) printf '%s' "$number" ;;
        *)  printf '%s' "$duration" ;;
    esac
}

# Each start_period is reported against the service it belongs to, so two
# services sharing one value are two findings, not one.
#
# Only services ut-install waits for are bound by its budget. An inference
# engine is left loading in the background, so its start_period answers to its
# own health check and not to the installer. Without this distinction the check
# would stay green for a reason that no longer holds.
check_no_service_starts_slower_than_the_installer_waits() {
    local budget entry line service role period seconds
    budget=$(grep -m1 -oE 'HEALTH_TIMEOUT="\$\{UT_HEALTH_TIMEOUT:-[0-9]+' "$REPO_ROOT/ut-install" 2>/dev/null \
        | grep -oE '[0-9]+$') || return 0
    [[ -n "$budget" ]] || return 0
    service=""
    role=""
    while IFS= read -r line; do
        entry=${line%"${line##*[![:space:]]}"}
        case "$entry" in
            "  "[a-z]*":")
                service=${entry#  }; service=${service%:}; role=""
                ;;
            *ut.role:*)
                role=$(printf '%s' "$entry" | sed 's/.*ut\.role:[[:space:]]*//; s/"//g')
                ;;
            *start_period:*)
                [[ "$role" != "inference" ]] || continue
                period=$(printf '%s' "$entry" | grep -oE '[0-9]+[hms]') || continue
                [[ -n "$period" ]] || continue
                seconds=$(seconds_in_duration "$period")
                (( seconds > budget )) || continue
                report "start-period-outlasts-the-install:${service:-unknown}" \
                    "${service:-a service} declares start_period ${period}, longer than the $(( budget / 60 )) minutes ut-install waits — the install gives up on a service that was never going to be ready in time"
                ;;
        esac
    done < "$REPO_ROOT/compose.yaml"
}

SERVICE_ROLES="control-plane backup inference"

judge_one_service_role() {
    local service=$1 role=$2
    [[ -n "$service" ]] || return 0
    if [[ -z "$role" ]]; then
        report "service-without-a-role:${service}" \
            "${service} declares no ut.role label — ut-install cannot tell whether to wait for it or let it start in the background, so it waits, and the install is as long as its slowest service"
        return 0
    fi
    case " ${SERVICE_ROLES} " in
        *" ${role} "*) return 0 ;;
    esac
    report "service-with-an-unknown-role:${service}" \
        "${service} declares ut.role ${role}, which is none of: ${SERVICE_ROLES} — ut-install would not know what to do with it"
}

# The role lives beside the service it describes. A list inside ut-install would
# drift the first time a service is added, and nothing would say so.
check_every_service_declares_its_role() {
    local line entry in_services=false service="" role=""
    while IFS= read -r line; do
        # compose.yaml carries trailing spaces on some service lines; matching
        # on the raw line silently skips those services.
        entry=${line%"${line##*[![:space:]]}"}
        case "$entry" in
            "services:")
                in_services=true
                continue
                ;;
            [a-z]*:*)
                if $in_services; then
                    judge_one_service_role "$service" "$role"
                fi
                in_services=false
                service=""
                role=""
                continue
                ;;
        esac
        $in_services || continue
        case "$entry" in
            "  "[a-z]*":")
                judge_one_service_role "$service" "$role"
                service=${entry#  }
                service=${service%:}
                role=""
                ;;
            *ut.role:*)
                role=$(printf '%s' "$line" | sed 's/.*ut\.role:[[:space:]]*//; s/"//g; s/[[:space:]]*$//')
                ;;
        esac
    done < "$REPO_ROOT/compose.yaml"
    if $in_services; then
        judge_one_service_role "$service" "$role"
    fi
}

# A backup deferred to a clock time cannot answer a health check that asks for a
# recent archive: the service stays unhealthy until that hour comes round.
check_the_first_backup_is_not_deferred_to_a_clock_time() {
    local begin
    begin=$(grep -m1 -oE 'DB01_BACKUP_BEGIN: "?\$\{BACKUP_BEGIN:-[^}]*\}"?' "$REPO_ROOT/compose.yaml" 2>/dev/null \
        | sed 's/.*:-//; s/}"*$//') || return 0
    [[ -n "$begin" ]] || return 0
    case "$begin" in
        +*) return 0 ;;
    esac
    report "first-backup-deferred:${begin}" \
        "the database backup defaults to ${begin}, a time of day: nothing is backed up before it comes, and the health check that looks for an archive cannot pass until then"
}

# A setting nothing interpolates reaches nothing. No compose file declares an
# env_file, so a value that is neither a render-time substitution nor an entry in
# an environment: block cannot travel to a container — whatever the image's code
# does with the name. Measured on 2026-09-21: release.env read
# AGENT_MAX_OUTPUT_TOKENS=24576 while the App Builder received 8192, thirty lines
# above under another name.
SETTINGS_READ_OUTSIDE_THE_STACK=(
    COMPOSE_FILE COMPOSE_PROFILES COMPOSE_PROJECT_NAME
    UT_RELEASE_VERSION UT_RELEASE_BUILT_AT
)

check_every_setting_reaches_something() {
    local key name exempt interpolated
    # The Caddyfile spells it {$VAR} and compose ${VAR}, and the overlays count
    # too: a setting used only by compose.compute.yaml is not dead.
    interpolated=$( {
        grep -ohE '\$\{[A-Za-z_][A-Za-z0-9_]*' "$REPO_ROOT"/compose*.yaml 2>/dev/null | tr -d '${'
        grep -ohE '\{\$[A-Za-z_][A-Za-z0-9_]*' "$REPO_ROOT/Caddyfile" "$REPO_ROOT"/caddy/*.caddy 2>/dev/null | tr -d '{$'
    } | sort -u )

    while read -r key; do
        [[ -n "$key" ]] || continue
        exempt=0
        for name in "${SETTINGS_READ_OUTSIDE_THE_STACK[@]}"; do
            [[ "$key" == "$name" ]] && exempt=1
        done
        (( exempt == 0 )) || continue
        grep -qx "$key" <<< "$interpolated" && continue
        report "setting-reaches-nothing:${key}" \
            "release.env declares ${key} and nothing interpolates it — the value cannot travel to any container"
    done <<< "$(env_keys)"
}

check_defaults_do_not_diverge() {
    local key defaults count
    while read -r key; do
        [[ -n "$key" ]] || continue
        defaults=$(grep -ohE "\\\$\{${key}:-[^}]*\}" "${COMPOSE_FILES[@]}" 2>/dev/null \
            | sed "s/^\\\${${key}:-//; s/}\$//" | sort -u)
        count=$(grep -c '' <<< "$defaults")
        (( count > 1 )) || continue
        report "divergent-default:${key}" \
            "${key} falls back to ${count} different values depending on the service — one of them is wrong"
    done <<< "$(grep -ohE '\$\{[A-Z_][A-Z0-9_]*:-' "${COMPOSE_FILES[@]}" 2>/dev/null \
        | sed 's/^\${//; s/:-$//' | sort -u)"
}

# A variable marked ${VAR:?} stops the stack when absent, which is the point —
# but only if whoever copies the template can see it needs a value. CA_PASSWORD
# was required by compose.yaml and in no template at all.
check_required_variables_appear_in_the_template() {
    local declared var
    declared=$(keys_a_machine_will_have)
    while read -r var; do
        [[ -n "$var" ]] || continue
        grep -qxF "$var" <<< "$declared" && continue
        report "required-variable-missing:${var}" \
            "${var} is required by a compose file, absent from release.env and generated by nothing — the stack will not start"
    done <<< "$(grep -ohE '\$\{[A-Z_][A-Z0-9_]*:\?' "${COMPOSE_FILES[@]}" 2>/dev/null \
        | sed 's/^\${//; s/:?$//' | sort -u)"
}

# Appearing in the template is not the same as having a value there. A required
# variable that is present but empty, and that ut-install does not generate,
# produces an install that stops on a name nobody has ever been asked for.
check_required_variables_have_a_value_or_are_generated() {
    local generated var value
    generated=$(keys_the_installer_generates)

    while read -r var; do
        [[ -n "$var" ]] || continue
        grep -qxF "$var" <<< "$generated" && continue
        # A variable absent from release.env makes grep exit 1, which pipefail
        # and set -e turn into a silent death rather than a finding.
        value=$(grep -m1 -E "^${var}=" "$RELEASE_ENV" 2>/dev/null | cut -d= -f2- | tr -d '"') || true
        [[ -n "$value" ]] && continue
        report "required-variable-unfilled:${var}" \
            "${var} is required by a compose file, empty in release.env, and generated by nothing — a fresh install stops on it"
    done <<< "$(grep -ohE '\$\{[A-Z_][A-Z0-9_]*:\?' "${COMPOSE_FILES[@]}" 2>/dev/null \
        | sed 's/^\${//; s/:?$//' | sort -u)"
}

check_variables_without_default_are_declared() {
    local declared required var
    declared=$(keys_a_machine_will_have)
    required=$(grep -ohE '\$\{[A-Za-z_][A-Za-z0-9_]*\}' "${COMPOSE_FILES[@]}" \
        | tr -d '${}' | sort -u)

    while read -r var; do
        [[ -n "$var" ]] || continue
        grep -qxF "$var" <<< "$declared" && continue
        report "undeclared-variable:${var}" \
            "\${${var}} has no default in the compose files and no value in release.env — the stack starts with it empty"
    done <<< "$required"
}

# A published port is reported by its effective value, with ${VAR:-default}
# collapsed to its default. Parameterising a port then leaves the identifier
# unchanged, so the baseline survives an edit that alters the form without
# altering the exposure.
published_port_entries() {
    awk '
        /^  [a-z0-9_-]+:/ { service = $1; sub(":", "", service) }
        /^    ports:/     { in_ports = 1; next }
        in_ports && /^      - / {
            entry = $2
            gsub(/"/, "", entry)
            while (match(entry, /\$\{[A-Za-z_][A-Za-z0-9_]*:-[^}]*\}/)) {
                spec = substr(entry, RSTART, RLENGTH)
                sub(/^\$\{[A-Za-z_][A-Za-z0-9_]*:-/, "", spec)
                sub(/\}$/, "", spec)
                entry = substr(entry, 1, RSTART - 1) spec substr(entry, RSTART + RLENGTH)
            }
            print service "|" entry
            next
        }
        in_ports && !/^      / { in_ports = 0 }
    ' "$@"
}

check_published_ports_are_allowed() {
    local service port_spec allowed
    allowed=$(grep -vE '^\s*(#|$)' "$ALLOWED_PORTS_FILE" 2>/dev/null || true)

    while IFS='|' read -r service port_spec; do
        [[ -n "$service" && -n "$port_spec" ]] || continue
        [[ "$port_spec" == 127.0.0.1:* || "$port_spec" == localhost:* ]] && continue
        grep -qxF "${service}:${port_spec}" <<< "$allowed" && continue
        report "unlisted-port:${service}:${port_spec}" \
            "${service} publishes ${port_spec} on every interface, and it is not in test/allowed-ports.txt"
    done <<< "$(published_port_entries "${COMPOSE_FILES[@]}")"
}

# Static on purpose: building a package here would cost more than the 0.87 s
# this whole file is allowed, so it reads the builder rather than its output.
check_the_package_stamps_the_commit_it_was_built_from() {
    local builder="$REPO_ROOT/packaging/build-deb.sh"
    [[ -f "$builder" ]] || return 0
    grep -q 'rev-parse' "$builder" && grep -q 'UT_RELEASE_VERSION=\\"\${stamp}' "$builder" && return 0
    report "package-version-without-commit" \
        "build-deb.sh writes UT_RELEASE_VERSION without the commit it was built from — a package that regresses cannot be traced back to its source"
}

check_images_are_pinned() {
    local key value
    while read -r key; do
        [[ "$key" == *_IMAGE ]] || continue
        value=$(env_raw_value "$key") || continue
        [[ -z "$value" ]] && continue
        [[ "$value" == *@sha256:* ]] && continue
        report "unpinned-image:${key}" \
            "${key}=${value} is a mutable reference — two boxes on the same version can differ"
    done <<< "$(env_keys)"
}

check_production_defaults() {
    local log_level
    log_level=$(env_raw_value LOG_LEVEL 2>/dev/null || true)
    if [[ "$log_level" == "DEBUG" || "$log_level" == "TRACE" ]]; then
        report "verbose-log-level:LOG_LEVEL" \
            "LOG_LEVEL=${log_level} in release.env — verbose logs on a customer's appliance"
    fi

    if grep -q 'maxmemory-policy allkeys-lru' "$REPO_ROOT/compose.yaml"; then
        report "queue-eviction:redis" \
            "redis runs allkeys-lru while holding the RQ queues — tasks can be evicted under memory pressure"
    fi
}

check_documented_paths_exist() {
    local path
    while read -r path; do
        [[ -n "$path" ]] || continue
        [[ -e "$REPO_ROOT/$path" ]] && continue
        report "missing-documented-path:${path}" \
            "README.md refers to ${path}, which does not exist"
    done <<< "$(grep -ohE '`[A-Za-z0-9_./-]+\.(ya?ml|sh|svg|caddy|example)`' "$REPO_ROOT/README.md" \
        | tr -d '`' | sort -u)"
}

read_baseline() {
    [[ -f "$BASELINE_FILE" ]] || return 0
    grep -vE '^\s*(#|$)' "$BASELINE_FILE" || true
}

compare_with_baseline() {
    local baseline found new=() stale=() id
    baseline=$(read_baseline)
    found=$(printf '%s\n' "${FINDING_IDS[@]+"${FINDING_IDS[@]}"}" | grep -v '^$' | sort -u || true)

    while read -r id; do
        [[ -n "$id" ]] || continue
        grep -qxF "$id" <<< "$baseline" || new+=("$id")
    done <<< "$found"

    while read -r id; do
        [[ -n "$id" ]] || continue
        grep -qxF "$id" <<< "$found" || stale+=("$id")
    done <<< "$baseline"

    local i
    if (( ${#new[@]} )); then
        printf '%s%sNew problems%s — not in test/known-issues.txt:\n\n' "$RED" "$BOLD" "$NC"
        for id in "${new[@]}"; do
            for i in "${!FINDING_IDS[@]}"; do
                [[ "${FINDING_IDS[$i]}" == "$id" ]] || continue
                printf '  %s%s%s\n    %s\n' "$BOLD" "$id" "$NC" "${FINDING_MESSAGES[$i]}"
                break
            done
        done
        printf '\nFix them, or add the identifier to test/known-issues.txt with a reason.\n\n'
    fi

    if (( ${#stale[@]} )); then
        printf '%s%sFixed problems still listed%s in test/known-issues.txt:\n\n' "$YELLOW" "$BOLD" "$NC"
        for id in "${stale[@]}"; do
            printf '  %s\n' "$id"
        done
        printf '\nRemove those lines. A baseline nobody prunes stops protecting anything.\n\n'
    fi

    if (( ${#new[@]} || ${#stale[@]} )); then
        return 1
    fi

    printf '%s%s invariant(s) hold%s' "$GREEN" "$(printf '%s\n' "$found" | grep -c . || true)" "$NC"
    printf ' — %s known issue(s) accepted in the baseline\n' "$(printf '%s\n' "$baseline" | grep -c . || true)"
}

services_the_stub_overlay_replaces() {
    awk '/^  [a-z][a-z-]*:$/ { svc=$1; sub(":","",svc) }
         /STUB_IMAGE/ && svc { print svc; svc="" }' "$REPO_ROOT/test/compose.stub.yaml" 2>/dev/null
}

ports_a_healthcheck_asks_for() {
    awk -v want="$1" '
        /^  [a-z][a-z-]*:$/ { svc=$1; sub(":","",svc); inblock=(svc==want) }
        inblock && /test:/ { print }
    ' "$REPO_ROOT/compose.yaml" | grep -oE '(localhost|127\.0\.0\.1):[0-9]+' | cut -d: -f2 | sort -u
}

# A stand-in that answers a port the real service no longer uses passes its
# healthcheck and proves nothing. This is what keeps test/stub.caddy honest when
# compose.yaml moves: the overlay is a second description of the same services,
# and a second description nobody compares is how the two drift apart.
check_the_stub_overlay_still_matches_the_services() {
    [[ -f "$REPO_ROOT/test/compose.stub.yaml" ]] || return 0

    local service port
    for service in $(services_the_stub_overlay_replaces); do
        if ! grep -qE "^  ${service}:$" "$REPO_ROOT/compose.yaml"; then
            report "stub-overlay-names-a-service-that-is-gone" \
                "test/compose.stub.yaml replaces '${service}', which compose.yaml no longer declares"
            continue
        fi
        for port in $(ports_a_healthcheck_asks_for "$service"); do
            grep -qE "^:${port}( |\{)" "$REPO_ROOT/test/stub.caddy" 2>/dev/null && continue
            report "stub-answers-no-port-for-a-healthcheck" \
                "${service} is healthchecked on port ${port}, which test/stub.caddy does not listen on"
        done
    done
}

main() {
    check_plaintext_secrets
    check_release_env_ships_no_secret
    check_compose_declares_no_secret_default
    check_healthcheck_asks_for_a_certified_name
    check_no_service_starts_slower_than_the_installer_waits
    check_every_service_declares_its_role
    check_the_first_backup_is_not_deferred_to_a_clock_time
    check_every_setting_reaches_something
    check_defaults_do_not_diverge
    check_required_variables_appear_in_the_template
    check_required_variables_have_a_value_or_are_generated
    check_variables_without_default_are_declared
    check_published_ports_are_allowed
    check_the_package_stamps_the_commit_it_was_built_from
    check_images_are_pinned
    check_production_defaults
    check_documented_paths_exist
    check_the_stub_overlay_still_matches_the_services
    compare_with_baseline
}

main "$@"
